# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.CharField(db_index=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='GameList',
            fields=[
                ('game_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('game_name', models.CharField(db_index=True, max_length=20)),
                ('num_player', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_list', models.BooleanField()),
                ('played', models.BooleanField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.GameList')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('comment', models.TextField(null=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.GameList')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(db_index=True, max_length=15, primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('pass_word', models.TextField()),
                ('user_id', models.IntegerField()),
                ('privacy', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
        migrations.AddField(
            model_name='playerlibrary',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='gamelist',
            order_with_respect_to='num_player',
        ),
        migrations.AddField(
            model_name='follow',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
        migrations.AddField(
            model_name='categories',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.GameList'),
        ),
        migrations.AlterUniqueTogether(
            name='playerlibrary',
            unique_together=set([('user_name', 'game_id')]),
        ),
    ]
